[phases.setup]
nixPkgs = ["nodejs", "ffmpeg"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["cd client && npm install && npm run build"]

[start]
cmd = "node server.js"
